const AD = 'AD';
const OWA = 'OWA';
const VPN = 'VPN';
const FWProxy = 'FW/PROXY';
const DNS = 'DNS';
const FILE_SHARING = 'FILE SHARING';
const EDR = 'EDR';

export const DETAILS_CARD = '@@listComponent/details_card';
export const VALUES_PROP = '@@listComponent/values_prop';
export const TOP3ANALYTICS_CARD = '@@listComponent/top3Analytics_card';
export const ANALYTICS = '@@listComponent/analytics';

export const entityNodebookID = 'EntityDetailAnalytics';
export const defaultSourceLog = 'panw';
export const dnsDefiningFeatures = {
  'sip': {
    'dns': ['num_dns_requests'],
    'panw': ['src_ip_03_count_connections'],
  },
  'sipdomain': {
    'dns': ['tot_dns_requests'],
    'panw': ['src_ip_01_tot_threat_sessions'],
  },
};

export const LogsTabs = [
  {
    'id': FWProxy,
    'title': 'FW/Proxy',
  },
  {
    'id': DNS,
    'title': 'DNS',
  },
  {
    'id': EDR,
    'title': 'EDR',
  },
  // {
  //   'id': IDS,
  //   'title': 'IDS',
  // },
  // {
  //   'id': NETFLOW,
  //   'title': 'NetFlow',
  // },
  // {
  //   'id': AD,
  //   'title': 'AD',
  // },
  // {
  //   'id': ENDPOINT,
  //   'title': 'Endpoint',
  // },
  // {
  //   'id': SERVER,
  //   'title': 'Serveer',
  // },
  // {
  //   'id': APPLICATION,
  //   'title': 'Application',
  // },
];

export const pipelineTabs = (pipeline) => {
  let tabs;
  switch (pipeline) {
    case 'useraccess':
      tabs = [
        {
          'id': FILE_SHARING,
          'title': 'File Sharing',
          'children': ['timedIndicator', 'fileIndicator'],
        },
        {
          'id': AD,
          'title': 'AD',
          'children': ['adIndicator'],
        },
        {
          'id': OWA,
          'title': 'OWA',
          'children': ['owaIndicator', 'owaTimeIndicator'],
        },
        {
          'id': VPN,
          'title': 'VPN',
          'children': ['vpnIndicator', 'vpnTimeIndicator'],
        },
      ];
      break;

    case 'domain':
      tabs = [
        {
          'id': FWProxy,
          'title': 'FW/Proxy',
          'children': [
            'idsIndicator',
            'dgaIndicator',
            'fqdnAnalytics',
            'domainIndicator',
            'statisticalFeatures',
          ],
        },
      ];
      break;
    case 'sip':
      tabs = [
        {
          'id': FWProxy,
          'title': 'FW/Proxy',
          'children': [
            'basicIndicator',
            'exfilterationIndicator',
            'timedIndicator',
            'idsIndicator',
            'torIndicator',
            'statisticalFeatures',
          ],
        },
        {
          'id': DNS,
          'title': 'DNS',
          'children': ['DNSNXIndicator', 'DNSDomainIndicator'],
        },
        {
          'id': AD,
          'title': 'AD',
          'children': ['adIndicator'],
        },
      ];
      break;

    case 'dip':
      tabs = [
        {
          'id': FWProxy,
          'title': 'FW/Proxy',
          'children': [
            'idsIndicator',
            'timedIndicator',
            'exfilterationIndicator',
          ],
        },
      ];
      break;

    case 'sipdomain':
      tabs = [
        {
          'id': FWProxy,
          'title': 'FW/Proxy',
          'children': [
            'idsIndicator',
            'dgaIndicator',
            'deliveryIndicator',
            'fqdnAnalytics',
            'domainIndicator',
            'domainAnalytics',
            'timedIndicator',
          ],
        },
        {
          'id': DNS,
          'title': 'DNS',
          'children': ['DNSNXIndicator', 'DNSDomainIndicator'],
        },
      ];
      break;

    case 'sipdip':
      tabs = [
        {
          'id': FWProxy,
          'title': 'FW/Proxy',
          'children': [
            'idsIndicator',
            'exfilterationIndicator',
            'icmpIndicator',
          ],
        },
      ];
      break;

    default:
      tabs = [];
      break;
  }

  return tabs;
};

export const tabsIdToName = (tab) => {
  switch (tab) {
    case 'basicIndicator':
      return 'Basic Indicator';

    case 'exfilterationIndicator':
      return 'Exfiltration';

    case 'timedIndicator':
    case 'owaTimeIndicator':
    case 'vpnTimeIndicator':
    case 'boxTimeIndicator':
      return 'Timed Transfer Indicators';

    case 'fileIndicator':
      return 'File Sharing Indicators';

    case 'threatIndicator':
      return 'Threat Indicators';

    case 'domainIndicator':
      return 'Domain Indicator';

    case 'deliveryIndicator':
      return 'Delivery Indicator';

    case 'domainAnalytics':
      return 'Domain Analytics';

    case 'icmpIndicator':
      return 'ICMP Exfiltration/Tunneling';

    case 'adIndicator':
      return 'AD Indicators';

    case 'owaIndicator':
      return 'OWA Indicators';

    case 'vpnIndicator':
      return 'VPN Indicators';

    case 'boxIndicator':
      return 'BOX Indicators';

    case 'idsIndicator':
      return 'IDS Indicators';

    case 'dgaIndicator':
      return 'DGA Indicators';

    case 'fqdnAnalytics':
      return 'FQDN Analytics';

    case 'statisticalFeatures':
      return 'Statistical Features';

    case 'DNSNXIndicator':
      return 'DNS NX Indicator';

    case 'DNSDomainIndicator':
      return 'DNS Domain Indicator';

    case 'torIndicator':
      return 'Tor Indicator';
    default:
      return tab;
  }
};

export const entityFeature = {
  'sip': {
    // updated 07/25/2018
    'basicIndicator': [
      'src_ip_35_count_destination_ips',
      'src_ip_01_distinct_dest_locations',
      'src_ip_03_count_connections',
      'src_ip_22_count_from_port_lt_1024',
      'src_ip_31_counter_applications',
    ],
    'exfilterationIndicator': [
      'src_ip_28_count_unanswered_connections',
      'src_ip_30_count_sent_bytes_e_packets_gt',
      'src_ip_29_count_received_bytes_e_packets_gt',
      'src_ip_23_count_distinct_from_ports',
      'src_ip_36_count_dns_udp_rule',
      'src_ip_37_count_dns_tcp_gt_1mb',
      'src_ip_39_count_http_dataxfer',
      'src_ip_38_count_nonhttp_dataxfer',
    ],
    /* Timed transfer indicators but not in use as of now */
    'timedIndicator': ['src_ip_34_std_duration',
      'src_ip_21_avg_packets_sent',
      'src_ip_09_std_bytes_received',
      'src_ip_12_avg_bytes_sent',
      'src_ip_12_std_bytes_sent',
      'src_ip_21_std_packets_sent',
      'src_ip_33_avg_interval',
      'src_ip_33_std_interval',
      'src_ip_18_std_packets_received',
      'src_ip_18_avg_packets_received',
      'src_ip_09_avg_bytes_received',
      'src_ip_34_avg_duration'],
    'idsIndicator': [
      'src_ip_47_count_blocked',
      'src_ip_49_count_allowed',
      'src_ip_48_count_blocked_url',
      'src_ip_45_count_malware',
      'src_ip_46_count_web',
      'src_ip_51_count_critical',
      'src_ip_52_count_high',
      'src_ip_53_count_medium',
      'src_ip_54_count_low',
      'src_ip_44_count_confirmed',
      'src_ip_55_count_pcap_available',
      'src_ip_40_source_country',
      'src_ip_56_distinct_destinations',
    ],
    'DNSNXIndicator': [
      'nxdomain_sld_entropy',
      'min_nxdomain_sld_length',
      'nxdomain_digit_ratio',
      'num_nxdomain_queries',
      'nxdomain_distinct_sld',
    ],
    'DNSDomainIndicator': [
      'sld_digit_ratio',
      'fqdn_avg_length',
      'fqdn_avg_num_special_chars',
      'max_dns_requests_hour',
      'num_dns_requests',
    ],
    'torIndicator': [
      'tor_sessions_unusual_port',
      'tor_sld_entropy',
      'tor_ratio_candidate_ips',
      'tor_sld_digit_ratio',
      'tor_sld_vowel_ratio',
      'tor_max_sld_length',
      'tor_char_continuity_rate',
      'tor_sld_length',
      'tor_distinct_sld_count',
      'tor_sessions_9000s_port',
      'tor_sld_others_ratio',
    ],
    'statisticalFeatures': [
      'src_ip_61_perc10_bytes_sent_1h',
      'src_ip_63_perc90_bytes_sent_1h',
      'src_ip_62_perc50_bytes_sent_1h',
    ],
    'adIndicator': [
      'ad_tot_failed_logins',
      'ad_num_distinct_users_authenticated',
      'ad_num_st',
      'ad_failed_login_ratio',
      'ad_tot_logins',
    ],
  },
  'dip': {
    // updated 07/25/2018
    // 'basicIndicator': [
    //   'dest_ip_04_counter_applications',
    //   'dest_ip_01_count_connections',
    //   'dest_ip_02_count_distinct_from_ips',
    //   'dest_ip_34_count_new_sips',
    // ],
    'idsIndicator': [
      'dest_ip_37_tot_threat_sessions',
      'dest_ip_38_count_confirmed',
      'dest_ip_39_count_malware',
      'dest_ip_40_count_web',
      'dest_ip_41_count_blocked',
      'dest_ip_42_count_blocked_url',
      'dest_ip_43_count_allowed',
      'dest_ip_44_distinct_threat_ids',
      'dest_ip_45_count_critical',
      'dest_ip_46_count_high',
      'dest_ip_47_count_medium',
      'dest_ip_48_count_low',
      'dest_ip_49_count_pcap_available',
    ],
    'exfilterationIndicator': [
      'dest_ip_01_count_connections',
      'dest_ip_02_count_distinct_from_ips',
      'dest_ip_03_count_distinct_to_ports',
      'dest_ip_04_counter_applications',
      'dest_ip_19_count_distinct_protocols',
      'dest_ip_07_count_to_port_gt_1024',
      'dest_ip_24_count_unanswered_connections',
      'dest_ip_25_count_received_bytes_e_packets_gt',
      'dest_ip_26_count_sent_bytes_e_packets_gt',
      'dest_ip_31_count_dns_udp_rule',
      'dest_ip_32_count_dns_tcp_gt_1mb',
    ],
    'timedIndicator': [
      'dest_ip_05_avg_duration',
      'dest_ip_05_std_duration',
      'dest_ip_12_avg_bytes',
      'dest_ip_12_std_bytes',
      'dest_ip_13_avg_bytes_sent',
      'dest_ip_13_std_bytes_sent',
      'dest_ip_14_avg_bytes_received',
      'dest_ip_14_std_bytes_received',
      'dest_ip_20_avg_packets',
      'dest_ip_20_std_packets',
      'dest_ip_21_avg_packets_sent',
      'dest_ip_21_std_packets_sent',
      'dest_ip_22_avg_packets_received',
      'dest_ip_22_std_packets_received',
    ],

  },
  'sipdip': {
    // updated 07/25/2018
    // 'basicIndicator': [
    //   'distinct_apps',
    //   'tot_bytes_sent',
    //   'tot_sessions',
    //   'tot_bytes_rcv',
    //   'reserved_ports',
    // ],
    'icmpIndicator': [
      'num_icmp_connections',
      'total_bytes_sent_icmp_connections',
      'total_bytes_received_icmp_connections',
      'total_packets_sent_icmp_connections',
      'total_packets_received_icmp_connections',
      'avg_bytes_sent_icmp_connections',
      'avg_bytes_received_icmp_connections',
      'std_bytes_sent_icmp_connections',
      'max_bytes_sent_icmp_connections',
      'max_bytes_received_icmp_connections',
      'avg_packets_sent_icmp_connections',
      'max_packets_sent_icmp_connections',
      'max_icmp_connections_hour',
      'max_icmp_connections_minute',
      'max_bytes_sent_icmp_connections_hour',
      'max_bytes_received_icmp_connections_hour',
      'max_bytes_sent_icmp_connections_minute',
      'max_bytes_received_icmp_connections_minute',
      'max_icmp_connections_same_bytes_sent',
      'max_icmp_connections_same_bytes_received',
      'avg_packet_sent_size_icmp_connections',
      'avg_packet_received_size_icmp_connections',
      'max_packet_sent_size_icmp_connections',
      'max_packet_received_size_icmp_connections',
    ],
    'exfilterationIndicator': [
      'tot_sessions',
      'distinct_apps',
      'count_distinct_to_ports',
      'count_distinct_protocols',
      'distinct_destinations',
      'count_dns_udp_rule',
      'count_dns_tcp_gt_1mb',
      'count_nonhttp_dataxfer',
      'count_http_dataxfer',
      'reserved_ports',
      'count_distinct_from_ports',
      'count_unanswered_connections',
      'count_received_bytes_e_packets_gt',
      'count_sent_bytes_e_packets_gt',
      'tot_bytes',
      'tot_bytes_sent',
      'tot_bytes_rcv',
      'avg_bytes_tot',
      'avg_bytes_sent',
      'avg_bytes_rcv',
      'avg_pkts_tot',
      'avg_pkts_sent',
      'avg_pkts_rcv',
      'avg_duration',
      'std_bytes_tot',
      'std_bytes_sent',
      'std_bytes_rcv',
      'std_pkts_tot',
      'std_pkts_sent',
      'std_pkts_rcv',
      'std_duration',
    ],
    // 'timedIndicator': [
    //   'avg_pkts_rcv',
    //   'std_interval',
    //   'avg_duration',
    //   'std_sessions_hr',
    //   'std_bytes_sent',
    //   'std_pkts_rcv',
    //   'std_bytes_rcv',
    //   'avg_bytes_rcv',
    //   'std_duration',
    //   'avg_sessions_hr',
    //   'avg_bytes_sent',
    //   'avg_interval',
    // ],
    'idsIndicator': [
      'tot_threat_sessions',
      'count_confirmed',
      'count_malware',
      'count_web',
      'count_blocked',
      'count_blocked_url',
      'count_allowed',
      'distinct_threat_ids',
      'count_critical',
      'count_high',
      'count_medium',
      'count_low',
      'count_pcap_available',
    ],
  },
  'domain': {
    // updated 07/25/2018
    'idsIndicator': [
      'distinct_destinations',
      'count_pcap_available',
      'count_critical',
      'count_high',
      'count_medium',
      'count_low',
      'count_allowed',
      'count_blocked',
      'count_blocked_url',
      'tot_threat_sessions',
      'count_confirmed',
      'count_web',
      'count_malware',
      'distinct_threat_ids',
    ],
    'dgaIndicator': [
      'dga_score',
    ],
    'fqdnAnalytics': [
      'fqdn_avg_num_special_chars',
      'avg_character_continuity_rate',
      'authority_avg_count_at_the_rate',
      'fqdn_avg_length',
    ],
    'domainIndicator': [
      'proxy_domain_age',
      'is_internationalized_domain',
      'sld_vowel_ratio',
      'sld_others_ratio',
      'sld_consonant_ratio',
      'sld_consonant_vowel_ratio',
      'num_phishing_names',
      'sld_length',
      'sld_digit_ratio',
      'tld_frequency',
      'alexa_rank',
    ],
    'statisticalFeatures': [
      'avg_bytes_rcv',
      'std_bytes_rcv',
      'min_bytes_rcv',
      'max_bytes_rcv',
    ],
  },
  'sipdomain': {
    // updated 07/25/2018
    'idsIndicator': [
      'src_ip_09_count_critical',
      'src_ip_10_count_high',
      'src_ip_11_count_medium',
      'src_ip_12_count_low',
      'src_ip_04_count_web',
      'src_ip_03_count_malware',
      'src_ip_02_count_confirmed',
      'src_ip_13_count_pcap_available',
      'src_ip_06_count_blocked_url',
      'src_ip_05_count_blocked',
      'src_ip_07_count_allowed',
      'src_ip_01_tot_threat_sessions',
      'src_ip_08_distinct_threat_ids',
    ],
    // 'timedIndicator': [
    //   'std_bytes_rcv',
    //   'avg_bytes_rcv',
    //   'max_bytes_rcv',
    //   'min_bytes_rcv',
    // ],
    'dgaIndicator': [
      'dga_score',
    ],
    'fqdnAnalytics': [
      'fqdn_avg_num_special_chars',
      'num_dns_invalid_fqdns',
      'fqdn_avg_length',
      'authority_avg_count_at_the_rate',
    ],
    'domainIndicator': [
      'max_dns_subdomain_length',
      'num_distinct_subdomains',
      'avg_subdomain_num_special_chars',
      'avg_subdomain_entropy_score',
      'avg_subdomain_entropy',
      'avg_subdomain_length',
      'num_dns_txt_queries',
      'num_dns_subdomains_excessive_length',
      'num_axfr_dns_requests',
      'num_distinct_nxdomain_subdomains',
      'num_udp_requests',
      'num_tcp_requests',
    ],
    'domainAnalytics': [
      'max_dns_requests_hour',
      'max_dns_requests_minute',
      'num_dns_requests',
    ],
    'deliveryIndicator': [
      'tld_frequency',
      'alexa_rank',
      'proxy_domain_age',
    ],
  },
  'useraccess': {
    'timedIndicator': [
      'fs_std_interval',
      'fs_avg_interval',
    ],
    'fileIndicator': [
      'fs_tot_alerts',
      'fs_user_agent_count',
      'fs_virus_detected',
      'fs_file_upload_count',
      'fs_source_code_upload_count',
      'fs_max_distance',
      'fs_max_interval',
      'fs_min_interval',
      'fs_tot_unique_ips',
      'fs_source_code_moved_count',
      'fs_tot_trash',
      'fs_source_code_deleted_count',
      'fs_ext_file_download_count',
      'fs_external_source_code_download',
      'fs_external_archives_download',
      'fs_source_code_modification_count',
      'fs_tot_copy',
      'fs_num_locations',
      'fs_max_speed',
      'fs_tot_workflow_download_violations',
      'fs_tot_workflow_upload_violations',
      'fs_tot_outside_collaborators',
      'fs_tot_inside_collaborators',
      'fs_tot_add_login_device',
      'fs_tot_logins',
      'fs_tot_failed_logins',
      'fs_tot_remove_login_device',
      'fs_tot_anonymous_links',
      'fs_tot_personal_collaborators',
    ],
    'adIndicator': [
      'ad_tot_failed_logins',
      'ad_tot_logins',
      'ad_num_account_lockouts',
      'ad_tot_interactive_logins',
      'ad_tot_network_logins',
      'ad_tot_other_logins',
      'ad_tot_logoffs',
      'ad_num_special_logons',
      'ad_num_network_attempts_logon',
      'ad_num_network_share_accessed',
      'ad_num_ipc_share_accessed',
      'ad_is_machine_account',
      'ad_num_credential_validation',
      'ad_num_st_requests',
      'ad_num_tgt_requests',
      'ad_tot_events',
      'ad_failed_login_ratio',
      'ad_st_request_ratio',
      'ad_tgt_request_ratio',
    ],
    'vpnIndicator': [
      'vpn_avg_src_distance',
      'vpn_min_src_distance',
      'vpn_max_src_distance',
      'vpn_num_ips',
      'vpn_tot_sessions',
      'vpn_tot_successful_auth',
      'vpn_tot_failed_auth',
      'vpn_tot_successful_access',
      'vpn_num_locations',
      'vpn_num_dhcp_ip4',
      'vpn_num_dhcp_ip6',
    ],
    'vpnTimeIndicator': [
      'vpn_avg_bytes_tot',
      'vpn_std_bytes_tot',
      'vpn_avg_bytes_sent',
      'vpn_std_bytes_sent',
      'vpn_avg_bytes_rcv',
      'vpn_std_bytes_rcv',
      'vpn_avg_duration',
      'vpn_std_duration',
    ],
    'fsTimeIndicator': [
      'interval',
    ],
    'owaTimeIndicator': [
      'owa_avg_interval',
      'owa_std_interval',
      'owa_avg_bytes_tot',
      'owa_std_bytes_tot',
      'owa_avg_bytes_rcv',
      'owa_std_bytes_rcv',
      'owa_avg_bytes_sent',
      'owa_std_bytes_sent',
    ],
    'owaIndicator': [
      'owa_tot_events',
      'owa_tot_owa',
      'owa_tot_user_agents',
      'owa_tot_referer',
      'owa_tot_uri',
      'owa_tot_operating_sys',
      'owa_tot_browsers',
      'owa_tot_sips',
      'owa_num_locations',
      'owa_tot_mobile',
      'owa_tot_domains',
      'owa_tot_unique_fingerprints',
      'owa_incorrect_password_owa',
      'owa_incorrect_password_autodiscover',
      'owa_succ_logins',
      'owa_max_distance',
      'owa_min_distance',
    ],
  },
  'request': {
    'basicIndicator': [
      'bytes_received',
      'bytes_sent',
      'status_code',
      'http_method',
    ],
    'idsIndicator': [
      'has_command_injection',
      'has_path_traversal',
      'is_restricted_path',
      'is_ua_sqli',
      'is_ua_xss',
      'num_duplicate_query_params',
      'num_query_params',
      'num_sqli_keywords',
      'num_xss_keywords',
      'qry_namelen_avg',
      'qry_namelen_max',
      'qry_namelen_min',
      'qry_namelen_std',
      'qry_valuelen_avg',
      'qry_valuelen_max',
      'qry_valuelen_min',
      'qry_valuelen_std',
      'query_length',
      'url_path_depth',
      'url_path_length',
    ],
  },
};

export const analyticsOptions = [
  {
    'content': 'Historical (30 days)',
    'id': 'historical_30_days',
  },
  {
    'content': 'Behaviour (24 hours)',
    'id': 'behaviour_24_hours',
  },
];

export const externalEnrichmentFormatData = [
  {
    'className': 'table__headerColumn',
    'isKey': false,
    'field': 'dip',
    'hidden': false,
    'label': 'DIP',
    'resizable': true,
    'intl': 'evp.logs.table.external.dip',
  },
  {
    'className': 'table__headerColumn',
    'isKey': false,
    'field': 'asn_id',
    'hidden': false,
    'label': 'ASN ID',
    'resizable': true,
    'intl': 'evp.logs.table.external.asn_id',
  },
  {
    'className': 'table__headerColumn',
    'isKey': false,
    'field': 'asn_provider',
    'hidden': false,
    'label': 'ASN Provider',
    'resizable': true,
    'intl': 'evp.logs.table.external.asn_provider',
  },
  {
    'className': 'table__headerColumn',
    'isKey': false,
    'field': 'location',
    'hidden': false,
    'label': 'Location',
    'resizable': true,
    'intl': 'evp.logs.table.external.location',
  },
];

export const historical30daysTableFormatData = (pipeline, modelType) => {
  const historicalData = [
    {
      'className': 'table__headerColumn',
      'isKey': true,
      'field': 'id',
      'hidden': true,
      'label': 'Id',
      'resizable': false,
      'intl': 'evp.historical.table.id',
      'activeOn': ['sipdip', 'dip', 'sip', 'hpa', 'user', 'useraccess', 'domain', 'sipdomain'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'date',
      'hidden': false,
      'label': 'Timestamp',
      'resizable': true,
      'intl': 'evp.historical.table.date',
      'activeOn': ['sipdip', 'dip', 'sip', 'hpa', 'user', 'useraccess', 'domain', 'sipdomain'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'user',
      'hidden': false,
      'label': 'User',
      'resizable': true,
      'intl': 'evp.historical.table.user',
      'activeOn': ['useraccess'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'user_id',
      'hidden': false,
      'label': 'User ID',
      'resizable': true,
      'intl': 'evp.historical.table.user_id',
      'activeOn': ['user'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'ipv4',
      'hidden': false,
      'label': 'IP Address',
      'resizable': true,
      'intl': 'evp.historical.table.ipv4',
      'activeOn': ['hpa'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': true,
      'field': 'srcip',
      'hidden': false,
      'label': 'Source IP',
      'resizable': true,
      'intl': 'evp.historical.table.srcip',
      'activeOn': ['sipdip', 'dip', 'sip', 'hpa', 'user', 'useraccess'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'domain',
      'hidden': false,
      'label': 'Domain',
      'resizable': true,
      'intl': 'evp.historical.table.domain',
      'activeOn': ['domain', 'sipdomain'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'dstip',
      'hidden': false,
      'label': 'Destination IP',
      'resizable': true,
      'intl': 'evp.historical.table.dstip',
      'activeOn': ['sipdip', 'dip'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'predicted_tag',
      'hidden': false,
      'label': 'Prediction',
      'resizable': true,
      'intl': 'evp.historical.table.predicted_tag',
      'activeOn': ['sipdip', 'dip', 'sip', 'hpa', 'user', 'useraccess'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'predicted_tag',
      'hidden': modelType === 'ranking',
      'label': 'Prediction',
      'resizable': true,
      'intl': 'evp.historical.table.predicted_tag',
      'activeOn': ['domain', 'sipdomain'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'predicted_prob',
      'hidden': false,
      'label': 'Confidence',
      'resizable': true,
      'intl': 'evp.historical.table.predicted_prob',
      'activeOn': ['sipdip', 'dip', 'sip', 'hpa', 'user', 'useraccess'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'score',
      'hidden': false,
      'label': 'Outlier Score',
      'resizable': true,
      'intl': 'evp.historical.table.score',
      'activeOn': ['sipdip', 'dip', 'sip', 'hpa', 'user', 'useraccess', 'domain', 'sipdomain'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'src_ip_03_count_connections',
      'hidden': false,
      'label': 'Number of Connections',
      'resizable': true,
      'intl': 'evp.historical.table.src_ip_03_count_connections',
      'activeOn': ['sip'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'src_ip_34_avg_duration',
      'hidden': false,
      'label': 'Average Duration',
      'resizable': true,
      'intl': 'evp.historical.table.src_ip_34_avg_duration',
      'activeOn': ['sip'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'src_ip_33_avg_interval',
      'hidden': false,
      'label': 'Average Interval',
      'resizable': true,
      'intl': 'evp.historical.table.src_ip_33_avg_interval',
      'activeOn': ['sip'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'dest_ip_01_count_connections',
      'hidden': false,
      'label': 'Number of Connections',
      'resizable': true,
      'intl': 'evp.historical.table.dest_ip_01_count_connections',
      'activeOn': ['dip'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'dest_ip_05_avg_duration',
      'hidden': false,
      'label': 'Average Duration',
      'resizable': true,
      'intl': 'evp.historical.table.dest_ip_05_avg_duration',
      'activeOn': ['dip'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'dest_ip_06_avg_interval',
      'hidden': false,
      'label': 'Average Interval',
      'resizable': true,
      'intl': 'evp.historical.table.dest_ip_06_avg_interval',
      'activeOn': ['dip'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'tot_sessions',
      'hidden': false,
      'label': 'Tot Sessions',
      'resizable': true,
      'intl': 'evp.historical.table.tot_sessions',
      'activeOn': ['sipdip'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'avg_duration',
      'hidden': false,
      'label': 'Average Duration',
      'resizable': true,
      'intl': 'evp.historical.table.avg_duration',
      'activeOn': ['sipdip'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'avg_interval',
      'hidden': false,
      'label': 'Average Interval',
      'resizable': true,
      'intl': 'evp.historical.table.avg_interval',
      'activeOn': ['sipdip'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'tot_bytes_sent',
      'hidden': false,
      'label': 'Total Bytes Sent',
      'resizable': true,
      'intl': 'evp.historical.table.tot_bytes_sent',
      'activeOn': ['sipdip', 'dip', 'sip', 'useraccess'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'tot_bytes_received',
      'hidden': false,
      'label': 'Total Bytes Received',
      'resizable': true,
      'intl': 'evp.historical.table.tot_bytes_received',
      'activeOn': ['sipdip', 'dip', 'sip', 'useraccess'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'src_ip_01_distinct_dest_locations',
      'hidden': false,
      'label': 'Number of Locations',
      'resizable': true,
      'intl': 'evp.historical.table.src_ip_01_distinct_dest_locations',
      'activeOn': ['sip'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'src_ip_35_count_destination_ips',
      'hidden': false,
      'label': '# Dest IPs',
      'resizable': true,
      'intl': 'evp.historical.table.src_ip_35_count_destination_ips',
      'activeOn': ['sip'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'src_ip_22_count_from_port_lt_1024',
      'hidden': false,
      'label': 'Reserved Ports',
      'resizable': true,
      'intl': 'evp.historical.table.src_ip_22_count_from_port_lt_1024',
      'activeOn': ['sip'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'src_ip_31_counter_applications',
      'hidden': false,
      'label': 'Distinct Apps',
      'resizable': true,
      'intl': 'evp.historical.table.src_ip_31_counter_applications',
      'activeOn': ['sip'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'dest_ip_04_counter_applications',
      'hidden': false,
      'label': 'Number of applications',
      'resizable': true,
      'intl': 'evp.historical.table.dest_ip_04_counter_applications',
      'activeOn': ['dip'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'dest_ip_02_count_distinct_from_ips',
      'hidden': false,
      'label': 'Number of IPs',
      'resizable': true,
      'intl': 'evp.historical.table.dest_ip_02_count_distinct_from_ips',
      'activeOn': ['dip'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'dest_ip_03_count_distinct_to_ports',
      'hidden': false,
      'label': 'Distinct to Ports',
      'resizable': true,
      'intl': 'evp.historical.table.dest_ip_03_count_distinct_to_ports',
      'activeOn': ['dip'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'distinct_apps',
      'hidden': false,
      'label': 'Distinct Apps',
      'resizable': true,
      'intl': 'evp.historical.table.distinct_apps',
      'activeOn': ['sipdip'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'reserved_ports',
      'hidden': false,
      'label': 'Reserved ports',
      'resizable': true,
      'intl': 'evp.historical.table.reserved_ports',
      'activeOn': ['sipdip'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'dstip_geo_location',
      'hidden': false,
      'label': 'Geo Location',
      'resizable': true,
      'intl': 'evp.historical.table.dstip_geo_location',
      'activeOn': ['sipdip', 'dip'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'login_success',
      'hidden': false,
      'label': 'Succ. Login',
      'resizable': true,
      'intl': 'evp.historical.table.login_success',
      'activeOn': ['hpa'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'login_failure',
      'hidden': false,
      'label': 'Failed Login',
      'resizable': true,
      'intl': 'evp.historical.table.login_failure',
      'activeOn': ['hpa'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'num_passwd',
      'hidden': false,
      'label': 'Password Resets',
      'resizable': true,
      'intl': 'evp.historical.table.num_passwd',
      'activeOn': ['hpa'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'num_userids',
      'hidden': false,
      'label': 'User IDs',
      'resizable': true,
      'intl': 'evp.historical.table.num_userids',
      'activeOn': ['hpa'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'num_chkout',
      'hidden': false,
      'label': 'Checkouts',
      'resizable': true,
      'intl': 'evp.historical.table.num_chkout',
      'activeOn': ['hpa', 'user'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'num_ipaddrs',
      'hidden': false,
      'label': 'Num Ips',
      'resizable': true,
      'intl': 'evp.historical.table.num_ipaddrs',
      'activeOn': ['user'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'max_ipscore',
      'hidden': false,
      'label': 'Max IP Score',
      'resizable': true,
      'intl': 'evp.historical.table.max_ipscore',
      'activeOn': ['user'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'min_reqs_log_to_chkout',
      'hidden': false,
      'label': 'Reqs to checkout',
      'resizable': true,
      'intl': 'evp.historical.table.min_reqs_log_to_chkout',
      'activeOn': ['user'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'num_reqs',
      'hidden': false,
      'label': 'Num Requests',
      'resizable': true,
      'intl': 'evp.historical.table.num_reqs',
      'activeOn': ['user'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'succ_login',
      'hidden': false,
      'label': 'Succ. Login',
      'resizable': true,
      'intl': 'evp.historical.table.succ_login',
      'activeOn': ['user'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'num_addresschg',
      'hidden': false,
      'label': 'Addr Change',
      'resizable': true,
      'intl': 'evp.historical.table.num_addresschg',
      'activeOn': ['user'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'addr_verify_fail',
      'hidden': false,
      'label': 'Address Verified',
      'resizable': true,
      'intl': 'evp.historical.table.addr_verify_fail',
      'activeOn': ['user'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'num_ship_over_exped',
      'hidden': false,
      'label': 'Shipping O/E',
      'resizable': true,
      'intl': 'evp.historical.table.num_ship_over_exped',
      'activeOn': ['user'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'num_addrs',
      'hidden': false,
      'label': 'Address Changes',
      'resizable': true,
      'intl': 'evp.historical.table.num_addrs',
      'activeOn': ['hpa'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'num_requests',
      'hidden': false,
      'label': 'Num Requests',
      'resizable': true,
      'intl': 'evp.historical.table.num_requests',
      'activeOn': ['hpa'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'bot_ratio',
      'hidden': false,
      'label': 'Bot Score',
      'resizable': true,
      'intl': 'evp.historical.table.bot_ratio',
      'activeOn': ['hpa'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'email_sim',
      'hidden': false,
      'label': 'Email Similarity',
      'resizable': true,
      'intl': 'evp.historical.table.email_sim',
      'activeOn': ['hpa'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'tot_successful_auth',
      'hidden': false,
      'label': 'Total Successful Auth',
      'resizable': true,
      'intl': 'evp.historical.table.tot_successful_auth',
      'activeOn': ['useraccess'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'tot_failed_auth',
      'hidden': false,
      'label': 'Total Failed Auth',
      'resizable': true,
      'intl': 'evp.historical.table.tot_failed_auth',
      'activeOn': ['useraccess'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'tot_duration',
      'hidden': false,
      'label': 'Total Duration',
      'resizable': true,
      'intl': 'evp.historical.table.tot_duration',
      'activeOn': ['useraccess'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'num_locations',
      'hidden': false,
      'label': 'Locations',
      'resizable': true,
      'intl': 'evp.historical.table.num_locations',
      'activeOn': ['useraccess'],
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'avg_src_distance',
      'hidden': false,
      'label': 'Avg Distance',
      'resizable': true,
      'intl': 'evp.historical.table.avg_src_distance',
      'activeOn': ['useraccess'],
    },
  ];

  const tableColumns = historicalData.filter(item => item.activeOn.includes(pipeline));

  return tableColumns;
};

export const relatedEntitiesTableFormatData = [
  {
    'className': 'table__headerColumn',
    'isKey': true,
    'field': 'id',
    'hidden': true,
    'label': 'Id',
    'resizable': false,
  },
  {
    'className': 'table__headerColumn',
    'isKey': false,
    'field': 'end_time',
    'hidden': false,
    'label': 'Date',
    'resizable': true,
  },
  {
    'className': 'table__headerColumn',
    'isKey': false,
    'field': 'entity_name',
    'hidden': false,
    'label': 'Entity',
    'resizable': true,
  },
  {
    'className': 'table__headerColumn',
    'isKey': false,
    'field': 'behavior',
    'hidden': true,
    'label': 'Behavior',
    'resizable': true,
  },
  {
    'className': 'table__headerColumn',
    'isKey': false,
    'field': 'threat_tactic',
    'hidden': false,
    'label': 'Threat Tactic',
    'resizable': true,
    'title': true,
  },
  {
    'className': 'table__headerColumn newTab',
    'isKey': false,
    'field': 'actions',
    'hidden': false,
    'label': 'Actions',
    'resizable': true,
    'sort': false,
  },
];

export const historical30DaysPipelineFeatures = {
  'sipdip': [
    'srcip',
    'dstip',
    'predicted_tag',
    'predicted_prob',
    'score',
    'tot_sessions',
    'avg_duration',
    'avg_interval',
    'tot_bytes_sent',
    'tot_bytes_received',
    'distinct_apps',
    'reserved_ports',
    'dstip_geo_location',
  ],
  'dip': [
    'srcip',
    'dstip',
    'predicted_tag',
    'predicted_prob',
    'score',
    'dest_ip_01_count_connections',
    'dest_ip_05_avg_duration',
    'dest_ip_06_avg_interval',
    'tot_bytes_sent',
    'tot_bytes_received',
    'dest_ip_04_counter_applications',
    'dest_ip_02_count_distinct_from_ips',
    'dest_ip_03_count_distinct_to_ports',
    'dstip_geo_location',
  ],
  'sip': [
    'srcip',
    'dstip',
    'predicted_tag',
    'predicted_prob',
    'score',
    'src_ip_03_count_connections',
    'src_ip_34_avg_duration',
    'src_ip_33_avg_interval',
    'tot_bytes_sent',
    'tot_bytes_received',
    'src_ip_01_distinct_dest_locations',
    'src_ip_35_count_destination_ips',
    'src_ip_22_count_from_port_lt_1024',
    'src_ip_31_counter_applications',
  ],
  'hpa': [
    'ipv4',
    'predicted_tag',
    'predicted_prob',
    'score',
    'login_success',
    'login_failure',
    'num_passwd',
    'num_userids',
    'num_chkout',
    'num_addrs',
    'num_requests',
    'bot_ratio',
    'email_sim',
  ],
  'request': [
    'ipv4',
    'predicted_tag',
    'predicted_prob',
    'score',
    'login_success',
    'login_failure',
    'num_passwd',
    'num_userids',
    'num_chkout',
    'num_addrs',
    'num_requests',
    'bot_ratio',
    'email_sim',
  ],
  'user': [
    'user_id',
    'predicted_tag',
    'predicted_prob',
    'score',
    'num_chkout',
    'num_ipaddrs',
    'max_ipscore',
    'min_reqs_log_to_chkout',
    'num_reqs',
    'succ_login',
    'num_addresschg',
    'addr_verify_fail',
    'num_ship_over_exped',
  ],
  'useraccess': [
    'user',
    'predicted_tag',
    'predicted_prob',
    'score',
    'tot_bytes_sent',
    'tot_bytes_received',
    'tot_successful_auth',
    'tot_failed_auth',
    'tot_duration',
    'num_locations',
    'avg_src_distance',
  ],
  'domain': [
    'domain',
    'predicted_tag',
    'score',
  ],
  'sipdomain': [
    'srcip',
    'domain',
    'predicted_tag',
    'score',
  ],
};

export const logsDataTableFormatData = {
  'FW/PROXY': [
    {
      'className': 'table__headerColumn',
      'isKey': true,
      'field': 'id',
      'hidden': true,
      'label': 'Id',
      'resizable': false,
      'intl': 'evp.logs.table.fw.id',
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'timestamp',
      'hidden': false,
      'label': 'UTC Time',
      'resizable': true,
      'intl': 'evp.logs.table.fw.timestamp',
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'srcip',
      'hidden': false,
      'label': 'Source IP',
      'resizable': true,
      'intl': 'evp.logs.table.fw.srcip',
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'dstip',
      'hidden': false,
      'label': 'Dest IP',
      'resizable': true,
      'intl': 'evp.logs.table.fw.dstip',
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'dst_port',
      'hidden': false,
      'label': 'Dest Port',
      'resizable': true,
      'intl': 'evp.logs.table.fw.dst_port',
    },
  ],
  'DNS': [
    {
      'className': 'table__headerColumn',
      'isKey': true,
      'field': 'uid',
      'hidden': false,
      'label': 'UID',
      'resizable': false,
      'intl': 'evp.logs.table.dns.uid',
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'source_ip',
      'hidden': false,
      'label': 'Source IP',
      'resizable': true,
      'intl': 'evp.logs.table.dns.source_ip',
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'query',
      'hidden': false,
      'label': 'Query',
      'resizable': true,
      'intl': 'evp.logs.table.dns.query',
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'response_code',
      'hidden': false,
      'label': 'Response Code',
      'resizable': true,
      'intl': 'evp.logs.table.dns.response_code',
    },
    {
      'className': 'table__headerColumn',
      'isKey': false,
      'field': 'time_generated',
      'hidden': false,
      'label': 'Time Generated',
      'resizable': true,
      'intl': 'evp.logs.table.dns.time_generated',
    },
  ],
  'EDR': [
    {
      'className': 'table__headerColumn',
      'isKey': true,
      'field': 'timestamp',
      'hidden': false,
      'label': 'Timestamp',
      'resizable': false,
      'intl': 'evp.logs.table.edr.timestamp',
    },
    {
      'className': 'table__headerColumn',
      'isKey': true,
      'field': 'date',
      'hidden': false,
      'label': 'Date',
      'resizable': false,
      'intl': 'evp.logs.table.edr.date',
    },
    {
      'className': 'table__headerColumn',
      'isKey': true,
      'field': 'log_source',
      'hidden': false,
      'label': 'Log Source',
      'resizable': false,
      'intl': 'evp.logs.table.edr.log_source',
    },
    {
      'className': 'table__headerColumn',
      'isKey': true,
      'field': 'ip',
      'hidden': false,
      'label': 'IP',
      'resizable': false,
      'intl': 'evp.logs.table.edr.ip',
    },
    {
      'className': 'table__headerColumn',
      'isKey': true,
      'field': 'hostname',
      'hidden': false,
      'label': 'Hostname',
      'resizable': false,
      'intl': 'evp.logs.table.edr.hostname',
    },
    {
      'className': 'table__headerColumn',
      'isKey': true,
      'field': 'username',
      'hidden': false,
      'label': 'Username',
      'resizable': false,
      'intl': 'evp.logs.table.edr.username',
    },
    {
      'className': 'table__headerColumn',
      'isKey': true,
      'field': 'os',
      'hidden': false,
      'label': 'OS',
      'resizable': false,
      'intl': 'evp.logs.table.edr.os',
    },
    {
      'className': 'table__headerColumn',
      'isKey': true,
      'field': 'process_name',
      'hidden': false,
      'label': 'Process Name',
      'resizable': false,
      'intl': 'evp.logs.table.edr.process_name',
    },
    {
      'className': 'table__headerColumn',
      'isKey': true,
      'field': 'process_path',
      'hidden': false,
      'label': 'Process Path',
      'resizable': false,
      'intl': 'evp.logs.table.edr.process_path',
    },
    {
      'className': 'table__headerColumn',
      'isKey': true,
      'field': 'process_md5',
      'hidden': false,
      'label': 'Process MD5',
      'resizable': false,
      'intl': 'evp.logs.table.edr.process_md5',
    },
  ],
};

export const dhcpDataFormat = [
  {
    'className': 'table__headerColumn',
    'isKey': false,
    'field': 'date',
    'hidden': false,
    'label': 'Date',
    'resizable': true,
    'intl': 'evp.dhcp.table.date',
  },
  {
    'className': 'table__headerColumn',
    'isKey': false,
    'field': 'ip',
    'hidden': false,
    'label': 'IP',
    'resizable': true,
    'intl': 'evp.dhcp.table.ip',
  },
  {
    'className': 'table__headerColumn',
    'isKey': false,
    'field': 'hostname',
    'hidden': false,
    'label': 'Hostname',
    'resizable': true,
    'intl': 'evp.dhcp.table.hostname',
  },
];
