import filterByMultipleTags from './filter-by-multiple-tags';

/**
 * @status: Complete
 * @sign-off-by: Alex Andries
 */
describe('filter-by-multiple-tags', () => {
  it('should return filtered data', () => {
    const data = [
      {
        'status': 'stopped',
        'uuid': 'e8cf0b58-a62b-11e8-a964-02c5862d1e7e',
        'handlers': {},
        'debug': true,
        'devicecategoryLabel': 'IAM',
        'dataSourceStatus': 'stopped',
        'devicetypeLabel': 'MS Active Directory',
        'disabled': true,
        'subtype': '',
        'filename': 'panw',
        'inputpath': '/mnt',
        'dataSourceDebug': true,
        'type': 'panw',
        'inputtype': 'file',
      },
      {
        'input.template.option': 'Network',
        'deviceip': 'Device Ip',
        'uuid': '0d157bee-a6ce-11e8-abe2-02c5862d1e7e',
        'devicename': 'Device Name',
        'devicecategory': 'Web',
        'output.outputTemplate': 'Kafka Output',
        'filename': 'proxy-brohttp',
        'port': '123',
        'debug': true,
        'input.Network_Raw.format': 'json',
        'input.template.suboption': 'Raw',
        'status': 'not started',
        'devicetimezone': 'utc',
        'output.Kafka.template': 'threat',
        'devicetype': 'proxy-brohttp',
        'inputtype': 'tcp',
        'output.Kafka.target': 'Driver node:66672',
        'devicecategoryLabel': 'Web',
        'devicetypeLabel': 'Bro-Http',
        'devicetimezoneLabel': 'UTC',
        'dataSourceStatus': 'not started',
        'dataSourceDebug': true,
      },
      {
        'input.template.option': 'Network',
        'deviceip': 'Device Ip',
        'uuid': '27e02adc-a6ce-11e8-abe2-02c5862d1e7e',
        'devicename': 'Device Name',
        'devicecategory': 'IAM',
        'output.outputTemplate': 'JSON Output',
        'devicesubtype': 'ad-winlogbeat',
        'handlers': {},
        'filename': 'ad-winlogbeat',
        'debug': false,
        'input.Network_Raw.format': 'json',
        'input.template.suboption': 'Raw',
        'status': 'not started',
        'devicetimezone': 'utc',
        'output.Kafka.template': 'threat',
        'devicetype': 'MS Active Directory',
        'inputtype': 'tcp',
        'port': '123',
        'output.JSON.path': '/mnt',
        'output.Kafka.target': 'Driver node:66672',
        'devicecategoryLabel': 'IAM',
        'devicetypeLabel': 'MS Active Directory',
        'devicesubtypeLabel': 'Winlogbeat',
        'devicetimezoneLabel': 'UTC',
        'dataSourceStatus': 'not started',
        'dataSourceDebug': false,
      },
      {
        'input.template.option': 'Network',
        'deviceip': 'Device Ip',
        'uuid': 'c54f2098-a6ce-11e8-abe2-02c5862d1e7e',
        'devicename': 'Device Name',
        'devicecategory': 'IAM',
        'output.outputTemplate': 'Kafka Output',
        'devicesubtype': 'ad-multilinexml',
        'filename': 'ad-multilinexml',
        'output.Kafka.template': 'threat',
        'input.Network_Raw.format': 'json',
        'input.template.suboption': 'Syslog',
        'status': 'not started',
        'devicetimezone': 'utc',
        'debug': true,
        'devicetype': 'MS Active Directory',
        'output.Kafka.target': 'Driver node:66672',
        'inputtype': 'tcp',
        'port': '123',
        'handlers': {},
        'devicecategoryLabel': 'IAM',
        'devicetypeLabel': 'MS Active Directory',
        'devicesubtypeLabel': 'Multilinexml',
        'devicetimezoneLabel': 'UTC',
        'dataSourceStatus': 'not started',
        'dataSourceDebug': true,
      },
      {
        'input.template.option': 'Network',
        'deviceip': 'Device Ip',
        'uuid': '03d7d7a6-a6cf-11e8-abe2-02c5862d1e7e',
        'devicename': 'Device Name',
        'devicecategory': 'IAM',
        'output.outputTemplate': 'Kafka Output',
        'filename': 'ad-multilinexml',
        'port': '123',
        'output.Kafka.template': 'threat',
        'input.Network_Raw.format': 'json',
        'input.template.suboption': 'Raw',
        'status': 'not started',
        'devicetimezone': 'utc',
        'debug': false,
        'devicetype': 'MS Active Directory',
        'output.Kafka.target': 'Driver node:66672',
        'inputtype': 'tcp',
        'devicesubtype': 'ad-multilinexml',
        'handlers': {},
        'devicecategoryLabel': 'IAM',
        'devicetypeLabel': 'MS Active Directory',
        'devicesubtypeLabel': 'Multilinexml',
        'devicetimezoneLabel': 'UTC',
        'dataSourceStatus': 'not started',
        'dataSourceDebug': false,
      },
      {
        'input.template.option': 'Network',
        'deviceip': 'Device Ip',
        'uuid': '01ff0d16-a6d2-11e8-abe2-02c5862d1e7e',
        'devicename': 'Device Name',
        'devicecategory': 'IAM',
        'output.outputTemplate': 'Kafka Output',
        'handlers': {},
        'filename': 'ad-multilinexml',
        'port': '123',
        'debug': true,
        'input.Network_Raw.format': 'json',
        'input.template.suboption': 'Raw',
        'status': 'not started',
        'devicetimezone': 'utc',
        'output.Kafka.template': 'threat',
        'devicetype': 'MS Active Directory',
        'inputtype': 'tcp',
        'devicesubtype': 'ad-multilinexml',
        'output.Kafka.target': 'Driver node:66672',
        'devicecategoryLabel': 'IAM',
        'devicetypeLabel': 'MS Active Directory',
        'devicesubtypeLabel': 'Multilinexml',
        'devicetimezoneLabel': 'UTC',
        'dataSourceStatus': 'not started',
        'dataSourceDebug': true,
      },
      {
        'input.template.option': 'Network',
        'deviceip': 'Device Ip',
        'uuid': '32832148-a6d2-11e8-abe2-02c5862d1e7e',
        'devicename': 'Device Name',
        'devicecategory': 'IAM',
        'output.outputTemplate': 'Kafka Output',
        'devicesubtype': 'ad-multilinexml',
        'handlers': {},
        'filename': 'ad-multilinexml',
        'debug': true,
        'input.Network_Raw.format': 'json',
        'input.template.suboption': 'Raw',
        'status': 'not started',
        'devicetimezone': 'utc',
        'output.Kafka.template': 'threat',
        'devicetype': 'MS Active Directory',
        'inputtype': 'tcp',
        'port': '123',
        'output.Kafka.target': 'Driver node:66672',
        'devicecategoryLabel': 'IAM',
        'devicetypeLabel': 'MS Active Directory',
        'devicesubtypeLabel': 'Multilinexml',
        'devicetimezoneLabel': 'UTC',
        'dataSourceStatus': 'not started',
        'dataSourceDebug': true,
      },
      {
        'input.template.option': 'Network',
        'deviceip': 'Device Ip',
        'uuid': '28dba05a-a6de-11e8-abe2-02c5862d1e7e',
        'devicename': 'Device Name',
        'devicecategory': 'IAM',
        'output.outputTemplate': 'Kafka Output',
        'handlers': {},
        'filename': 'ad-multilinexml',
        'port': '123',
        'debug': true,
        'input.Network_Raw.format': 'json',
        'input.template.suboption': 'Raw',
        'status': 'not started',
        'devicetimezone': 'utc',
        'output.Kafka.template': 'threat',
        'devicetype': 'MS Active Directory',
        'inputtype': 'tcp',
        'devicesubtype': 'ad-multilinexml',
        'output.Kafka.target': 'Driver node:66672',
        'devicecategoryLabel': 'IAM',
        'devicetypeLabel': 'MS Active Directory',
        'devicesubtypeLabel': 'Multilinexml',
        'devicetimezoneLabel': 'UTC',
        'dataSourceStatus': 'not started',
        'dataSourceDebug': true,
      },
      {
        'input.template.option': 'Network',
        'deviceip': 'Device Ip',
        'uuid': '8ed91a84-a771-11e8-a332-02c5862d1e7e',
        'devicename': 'Device Name new',
        'devicecategory': 'IAM',
        'output.outputTemplate': 'Kafka Output',
        'devicesubtype': 'ad-multilinexml',
        'filename': 'ad-multilinexml',
        'output.Kafka.template': 'threat',
        'input.Network_Raw.format': 'json',
        'input.template.suboption': 'Raw',
        'status': 'not started',
        'devicetimezone': 'utc',
        'debug': true,
        'devicetype': 'MS Active Directory',
        'output.Kafka.target': 'Driver node:66672',
        'inputtype': 'tcp',
        'port': '123',
        'handlers': {},
        'devicecategoryLabel': 'IAM',
        'devicetypeLabel': 'MS Active Directory',
        'devicesubtypeLabel': 'Multilinexml',
        'devicetimezoneLabel': 'UTC',
        'dataSourceStatus': 'not started',
        'dataSourceDebug': true,
      }];

    const expectedResults = [
      {
        'dataSourceDebug': true,
        'dataSourceStatus': 'not started',
        'debug': true,
        'devicecategory': 'Web',
        'devicecategoryLabel': 'Web',
        'deviceip': 'Device Ip',
        'devicename': 'Device Name',
        'devicetimezone': 'utc',
        'devicetimezoneLabel': 'UTC',
        'devicetype': 'proxy-brohttp',
        'devicetypeLabel': 'Bro-Http',
        'filename': 'proxy-brohttp',
        'input.Network_Raw.format': 'json',
        'input.template.option': 'Network',
        'input.template.suboption': 'Raw',
        'inputtype': 'tcp',
        'output.Kafka.target': 'Driver node:66672',
        'output.Kafka.template': 'threat',
        'output.outputTemplate': 'Kafka Output',
        'port': '123',
        'status': 'not started',
        'uuid': '0d157bee-a6ce-11e8-abe2-02c5862d1e7e',
      }];

    expect(filterByMultipleTags(data, ['http'])).toEqual(expectedResults);
  });
});