export default {
  FETCH_REPORTS: '@@rest/FETCH_REPORTS',
  FETCH_REPORTS_SUCCESS: '@@rest/FETCH_REPORTS_SUCCESS',
  FETCH_REPORTS_FAILED: '@@rest/FETCH_REPORTS_FAILED',

  FETCH_REPORT_SUMMARY: '@@rest/FETCH_REPORT_SUMMARY',
  FETCH_REPORT_SUMMARY_SUCCESS: '@@rest/FETCH_REPORT_SUMMARY_SUCCESS',
  FETCH_REPORT_SUMMARY_FAILED: '@@rest/FETCH_REPORT_SUMMARY_FAILED',

  FETCH_REPORT_SUMMARY_DATES: '@@rest/FETCH_REPORT_SUMMARY_DATES',
  FETCH_REPORT_SUMMARY_DATES_SUCCESS: '@@rest/FETCH_REPORT_SUMMARY_DATES_SUCCESS',
  FETCH_REPORT_SUMMARY_DATES_FAILED: '@@rest/FETCH_REPORT_SUMMARY_DATES_FAILED',

  CREATE_NEW_REPORT: '@@rest/CREATE_NEW_REPORT',
  CREATE_NEW_REPORT_SUCCESS: '@@rest/CREATE_NEW_REPORT_SUCCESS',
  CREATE_NEW_REPORT_FAILED: '@@rest/CREATE_NEW_REPORT_FAILED',

  EDIT_REPORT: '@@rest/EDIT_REPORT',
  EDIT_REPORT_SUCCESS: '@@rest/EDIT_REPORT_SUCCESS',
  EDIT_REPORT_FAILED: '@@rest/EDIT_REPORT_FAILED',

  DELETE_REPORT: '@@rest/DELETE_REPORT',
  DELETE_REPORT_SUCCESS: '@@rest/DELETE_REPORT_SUCCESS',
  DELETE_REPORT_FAILED: '@@rest/DELETE_REPORT_FAILED',

  GET_REPORT_BYID: '@@rest/GET_REPORT_BYID',
  GET_REPORT_BYID_SUCCESS: '@@rest/GET_REPORT_BYID_SUCCESS',
  GET_REPORT_BYID_FAILED: '@@rest/GET_REPORT_BYID_FAILED',

  FETCH_REPORT_RESULTS: '@@rest/FETCH_REPORT_RESULTS',
  FETCH_REPORT_RESULTS_SUCCESS: '@@rest/FETCH_REPORT_RESULTS_SUCCESS',
  FETCH_REPORT_RESULTS_FAILED: '@@rest/FETCH_REPORT_RESULTS_FAILED',

  FETCH_REPORT_RESULTS_CSV: '@@rest/FETCH_REPORT_RESULTS_CSV',
  FETCH_REPORT_RESULTS_CSV_SUCCESS: '@@rest/FETCH_REPORT_RESULTS_CSV_SUCCESS',
  FETCH_REPORT_RESULTS_CSV_FAILED: '@@rest/FETCH_REPORT_RESULTS_CSV_FAILED',

  RESET_REPORTS_DETAIL_STATE: '@@setter/RESET_REPORTS_DETAIL_STATE',
  RESET_DOWNLOAD_CSV: '@@setter/RESET_DOWNLOAD_CSV',

  ON_DEMAND: '@@rest/ON_DEMAND',
  ON_DEMAND_SUCCESS: '@@rest/ON_DEMAND_SUCCESS',
  ON_DEMAND_FAILED: '@@rest/ON_DEMAND_FAILED',
};
