export default {
  USER_IS_LOGGED_IN_START: '@@session/USER_IS_LOGGED_IN_START',
  USER_IS_LOGGED_IN_SUCCESS: '@@session/USER_IS_LOGGED_IN_SUCCESS',
  USER_IS_LOGGED_IN_FAIL: '@@session/USER_IS_LOGGED_IN_FAIL',

  USER_LOGIN_START: '@@session/USER_LOGIN_START',
  USER_LOGIN_SUCCESS: '@@session/USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL: '@@session/USER_LOGIN_FAIL',

  USER_LOGOUT_START: '@@session/USER_LOGOUT_START',
  USER_LOGOUT_SUCCESS: '@@session/USER_LOGOUT_SUCCESS',
  USER_LOGOUT_FAIL: '@@session/USER_LOGOUT_FAIL',
};
