export default {
  FETCH_MALICIOUS_BEHAVIOR: '@@rest/FETCH_MALICIOUS_BEHAVIOR',
  FETCH_MALICIOUS_BEHAVIOR_COMPLETE: '@@rest/FETCH_MALICIOUS_BEHAVIOR_COMPLETE',
  FETCH_MALICIOUS_BEHAVIOR_FAILED: '@@rest/FETCH_MALICIOUS_BEHAVIOR_FAILED',
};
