export const suspiciousColumns = [
  {
    'className': 'table__headerColumn',
    'isKey': true,
    'field': 'id',
    'hidden': true,
    'label': 'Id',
    'resizable': false,
    'intl': 'suspicious.table.id',
  },
  {
    'className': 'table__headerColumn',
    'isKey': false,
    'field': 'start_time_formatted',
    'hidden': false,
    'label': 'Log Date',
    'resizable': true,
    'width': 100,
    'intl': 'suspicious.table.start_time_formatted',
  },
  {
    'className': 'table__headerColumn--entity',
    'isKey': true,
    'field': 'entity_name',
    'hidden': false,
    'label': 'Entity',
    'resizable': true,
    'tooltip': 'investigate',
    'width': 200,
    'intl': 'suspicious.table.entity_name',
  },
  {
    'className': 'table__headerColumn',
    'isKey': false,
    'field': 'method_score',
    'hidden': false,
    'label': 'Score',
    'resizable': true,
    'intl': 'suspicious.table.method_score',
  },
  {
    'className': 'table__headerColumn--highlighted',
    'isKey': false,
    'field': 'method_name',
    'hidden': false,
    'label': 'Type',
    'resizable': true,
    'intl': 'suspicious.table.method_name',
  },
  {
    'className': 'table__headerColumn--actions',
    'isKey': false,
    'field': 'actions',
    'hidden': false,
    'label': 'Actions',
    'resizable': true,
    'sort': false,
    'width': 250,
    'intl': 'suspicious.table.actions',
  },
];
