export default {
  REFRESH_MALICIOUS_BEHAVIOR: '@@rest/REFRESH_MALICIOUS_BEHAVIOR',
  REFRESH_MALICIOUS_BEHAVIOR_COMPLETE: '@@rest/REFRESH_MALICIOUS_BEHAVIOR_COMPLETE',
  REFRESH_MALICIOUS_BEHAVIOR_FAILED: '@@rest/REFRESH_MALICIOUS_BEHAVIOR_FAILED',

  REFRESH_SUSPICIOUS_BEHAVIOR: '@@rest/REFRESH_SUSPICIOUS_BEHAVIOR',
  REFRESH_SUSPICIOUS_BEHAVIOR_COMPLETE: '@@rest/REFRESH_SUSPICIOUS_BEHAVIOR_COMPLETE',
  REFRESH_SUSPICIOUS_BEHAVIOR_FAILED: '@@rest/REFRESH_SUSPICIOUS_BEHAVIOR_FAILED',

  FETCH_SUMMARY: '@@rest/FETCH_SUMMARY',
  FETCH_SUMMARY_BY_CHUNK: '@@rest/FETCH_SUMMARY_BY_CHUNK',
  FETCH_SUMMARY_COMPLETE: '@@rest/FETCH_SUMMARY_COMPLETE',
  FETCH_SUMMARY_CHUNK_COMPLETE: '@@rest/FETCH_SUMMARY_CHUNK_COMPLETE',
  FETCH_SUMMARY_FAILED: '@@rest/FETCH_SUMMARY_FAILED',
  REFRESH_SUMMARY: '@@rest/REFRESH_SUMMARY',
  REFRESH_SUMMARY_COMPLETE: '@@rest/REFRESH_SUMMARY_COMPLETE',
  REFRESH_SUMMARY_CHUNK_COMPLETE: '@@rest/REFRESH_SUMMARY_CHUNK_COMPLETE',
  REFRESH_SUMMARY_FAILED: '@@rest/REFRESH_SUMMARY_FAILED',

  REFRESH_DASHBOARD: 'REFRESH_DASHBOARD',
};
