export default {
  FETCH_PERFORMANCE_DATA: '@@rest/FETCH_PERFORMANCE_DATA',
  FETCH_PERFORMANCE_DATA_COMPLETE: '@@rest/FETCH_PERFORMANCE_DATA_COMPLETE',
  FETCH_PERFORMANCE_DATA_FAILED: '@@rest/FETCH_PERFORMANCE_DATA_FAILED',
};
