export default {
  GET_SUMMARY_DATA_BEGIN_LOADING: '@@logManager/GET_SUMMARY_DATA_BEGIN_LOADING',
  GET_SUMMARY_DATA_COMPLETE_LOADING: '@@logManager/GET_SUMMARY_DATA_COMPLETE_LOADING',

  GET_DATA_SOURCES_BEGIN_LOADING: '@@logManager/GET_DATA_SOURCES_BEGIN_LOADING',
  GET_DATA_SOURCES_COMPLETE_LOADING: '@@logManager/GET_DATA_SOURCES_COMPLETE_LOADING',
  GET_DATA_SOURCES_FAIL_LOADING: '@@logManager/GET_DATA_SOURCES_FAIL_LOADING',

  GET_DATA_CONFIG_BEGIN_LOADING: '@@logManager/GET_DATA_CONFIG_BEGIN_LOADING',
  GET_DATA_CONFIG_COMPLETE_LOADING: '@@logManager/GET_DATA_CONFIG_COMPLETE_LOADING',
  GET_DATA_CONFIG_FAIL_LOADING: '@@logManager/GET_DATA_CONFIG_FAIL_LOADING',

  ADD_DATA_SOURCE_BEGIN_SENDING: '@@logManager/ADD_DATA_SOURCE_BEGIN_SENDING',
  ADD_DATA_SOURCE_COMPLETE_SENDING: '@@logManager/ADD_DATA_SOURCE_COMPLETE_SENDING',
  ADD_DATA_SOURCE_FAIL_SENDING: '@@logManager/ADD_DATA_SOURCE_FAIL_SENDING',

  UPDATE_DATA_SOURCE_BEGIN_SENDING: '@@logManager/UPDATE_DATA_SOURCE_BEGIN_SENDING',
  UPDATE_DATA_SOURCE_COMPLETE_SENDING: '@@logManager/UPDATE_DATA_SOURCE_COMPLETE_SENDING',
  UPDATE_DATA_SOURCE_FAIL_SENDING: '@@logManager/UPDATE_DATA_SOURCE_FAIL_SENDING',

  START_DATA_SOURCE_BEGIN_SENDING: '@@logManager/START_DATA_SOURCE_BEGIN_SENDING',
  START_DATA_SOURCE_COMPLETE_SENDING: '@@logManager/START_DATA_SOURCE_COMPLETE_SENDING',
  START_DATA_SOURCE_FAIL_SENDING: '@@logManager/START_DATA_SOURCE_FAIL_SENDING',

  STOP_DATA_SOURCE_BEGIN_SENDING: '@@logManager/STOP_DATA_SOURCE_BEGIN_SENDING',
  STOP_DATA_SOURCE_COMPLETE_SENDING: '@@logManager/STOP_DATA_SOURCE_COMPLETE_SENDING',
  STOP_DATA_SOURCE_FAIL_SENDING: '@@logManager/STOP_DATA_SOURCE_FAIL_SENDING',

  DELETE_DATA_SOURCE_BEGIN_SENDING: '@@logManager/DELETE_DATA_SOURCE_BEGIN_SENDING',
  DELETE_DATA_SOURCE_COMPLETE_SENDING: '@@logManager/DELETE_DATA_SOURCE_COMPLETE_SENDING',
  DELETE_DATA_SOURCE_FAIL_SENDING: '@@logManager/DELETE_DATA_SOURCE_FAIL_SENDING',
};
