export const maliciousColumns = [
  {
    'className': 'table__headerColumn',
    'isKey': true,
    'field': 'hash',
    'hidden': true,
    'label': 'Hash',
    'resizable': false,
    'intl': 'malicious.table.hash',
  },
  {
    'className': 'table__headerColumn',
    'isKey': false,
    'field': 'start_time_formatted',
    'hidden': false,
    'label': 'Log Date',
    'resizable': true,
    'width': 100,
    'intl': 'malicious.table.start_time_formatted',
  },
  {
    'className': 'table__headerColumn--entity',
    'isKey': false,
    'field': 'entity_name',
    'hidden': false,
    'label': 'Entity',
    'resizable': true,
    'tooltip': 'investigate',
    'intl': 'malicious.table.entity_name',
  },
  {
    'className': 'table__headerColumn',
    'isKey': false,
    'field': 'score',
    'hidden': false,
    'label': 'Score',
    'resizable': true,
    'width': 150,
    'intl': 'malicious.table.score',
  },
  {
    'className': 'table__headerColumn--highlighted',
    'isKey': false,
    'field': 'threat',
    'hidden': false,
    'label': 'Threat Tactic',
    'resizable': true,
    'width': 220,
    'intl': 'malicious.table.threat',
  },
  {
    'className': 'table__headerColumn--actions',
    'isKey': false,
    'field': 'actions',
    'hidden': false,
    'label': 'Actions',
    'resizable': true,
    'sort': false,
    'width': 250,
    'intl': 'malicious.table.actions',
  },
];
