export default {
  FETCH_SUSPICIOUS_BEHAVIOR: '@@rest/FETCH_SUSPICIOUS_BEHAVIOR',
  FETCH_SUSPICIOUS_BEHAVIOR_COMPLETE: '@@rest/FETCH_SUSPICIOUS_BEHAVIOR_COMPLETE',
  FETCH_SUSPICIOUS_BEHAVIOR_FAILED: '@@rest/FETCH_SUSPICIOUS_BEHAVIOR_FAILED',
};
