export default {
  FETCH_SEARCH_DATA: '@@explodedView/FETCH_SEARCH_DATA',
  SET_SEARCH_DATA: '@@explodedView/SET_SEARCH_DATA',
  SET_MODEL_NAME: '@@explodedView/SET_MODEL_NAME',

  FETCH_CLUSTER_RELATIONS: '@@explodedView/FETCH_CLUSTER_RELATIONS',
  SET_CLUSTER_RELATIONS: '@@explodedView/SET_CLUSTER_RELATIONS',

  SET_HISTORICAL_DATA: '@@explodedView/SET_HISTORICAL_DATA',

  SET_LABELS_HISTORY: '@@explodedView/SET_LABELS_HISTORY',
  FETCH_LABELS_HISTORY: '@@explodedView/FETCH_LABELS_HISTORY',

  FETCH_RELATED_ENTITIES_DATA: '@@explodedView/FETCH_RELATED_ENTITIES_DATA',
  SET_RELATED_ENTITIES_DATA: '@@explodedView/SET_RELATED_ENTITIES_DATA',

  GET_ENTITY_INFO: '@@explodedView/GET_ENTITY_INFO',

  GET_NX_DOMAINS: '@@explodedView/GET_NX_DOMAINS',

  FETCH_VULNERABILITY_REPORT_DATA: '@@explodedView/FETCH_VULNERABILITY_REPORT_DATA',
  SET_VULNERABILITY_REPORT_DATA: '@@explodedView/SET_VULNERABILITY_REPORT_DATA',

  SET_FW_LOGS_DATA: '@@explodedView/SET_FW_LOGS_DATA',
  SET_DNS_LOGS_DATA: '@@explodedView/SET_DNS_LOGS_DATA',

  GET_EDR_LOGS_DATA: '@@rest/GET_EDR_LOGS_DATA',
  GET_EDR_LOGS_DATA_SUCCESS: '@@rest/GET_EDR_LOGS_DATA_SUCCESS',
  GET_EDR_LOGS_DATA_FAILED: '@@rest/GET_EDR_LOGS_DATA_FAILED',

  SET_LABEL_START: '@@rest/SET_LABEL_START',
  SET_LABEL_COMPLETE: '@@rest/SET_LABEL_COMPLETE',

  GET_DHCP_DATA: '@@rest/GET_DHCP_DATA',
  GET_DHCP_DATA_SUCCESS: '@@rest/GET_DHCP_DATA_SUCCESS',
  GET_DHCP_DATA_FAILED: '@@rest/GET_DHCP_DATA_FAILED',

  GET_DETAILS_DATA: '@@rest/GET_DETAILS_DATA',
  SET_DETAILS_DATA: '@@rest/SET_DETAILS_DATA',
  GET_DETAILS_DATA_FAILED: '@@rest/GET_DETAILS_DATA_FAILED',
};
